runtime: python310
automatic_scaling:
  target_cpu_utilization: 0.90
  max_instances: 1
instance_class: F2
entrypoint: gunicorn -b :8080 main:server
env_variables:
  BUCKET_NAME: 'cs163-website.appspot.com'
